# Generated by Django 3.2.5 on 2021-08-31 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_comentario_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='escritor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='wall_app.user'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='wall_app.mensaje'),
        ),
    ]
